import { FooterContent } from './actions/getData'
import Footer from './components/Footer/Footer'
import Navbar from './components/navbar/Navbar'
import './globals.css'
import localFont from '@next/font/local';

const Caprasimo = localFont({
  src: '../public/FontType/Cambria-Regular.woff2',
  variable: "--title-font",
});
const CambriaMath = localFont({
  src: '../public/FontType/Caprasimo-Regular.woff2',
  variable: "--content-font",
});

export const metadata = {
  title: 'Donjon Fauna',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${Caprasimo.variable} ${CambriaMath.variable}`}>
      <body>
        <Navbar/>
        {children}
        <Footer 
          title={FooterContent.title}
          socialMedia={FooterContent.socialMedia}
          footer={FooterContent.footer}
          />
      </body>
    </html>
  )
}
